---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-facts-app-canary-v2
  namespace: random-facts-app-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      lab: random-facts-app-canary
  template:
    metadata:
      labels:
        lab: random-facts-app-canary
        version: v2
    spec:
      containers:
      - name: random-facts-app
        image: us-central1-docker.pkg.dev/marson-37767/marson-registry/random-facts-app:2.0
        ports:
        - containerPort: 5000
